In [1]:
import pandas as pd 
import numpy as np 
import geopandas as gpd 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
%matplotlib inline

In [2]:
gdf = gpd.read_file('/Users/ananyarajesh/Downloads/nynta2020_23a/nynta2020.shp')

In [3]:
gdf.rename(columns={'BoroName': 'County Name'}, inplace=True)

In [4]:
gdf

,BoroCode,County Name,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry
0,3,Brooklyn,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ..."
1,3,Brooklyn,047,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28158.316197,2.886214e+07,"POLYGON ((994849.011 203499.267, 994911.093 20..."
2,3,Brooklyn,047,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.280262,1.520896e+07,"POLYGON ((998047.210 196303.325, 998157.901 19..."
3,3,Brooklyn,047,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.772815,5.226621e+07,"POLYGON ((1005302.497 199455.730, 1005307.792 ..."
4,3,Brooklyn,047,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.504911,9.982322e+06,"POLYGON ((986367.735 190549.239, 985813.835 19..."
...,...,...,...,...,...,...,...,...,...,...,...,...
257,5,Staten Island,085,SI0391,Freshkills Park (South),FrshklPK_S,9,SI03,SI03 South Shore (CD 3 Approximation),33945.420291,4.775877e+07,"POLYGON ((928531.433 150471.714, 929005.649 15..."
258,5,Staten Island,085,SI9561,Fort Wadsworth,FtWdswrth,6,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,14816.104455,9.864874e+06,"POLYGON ((967656.829 155637.132, 967549.629 15..."
259,5,Staten Island,085,SI9591,Hoffman & Swinburne Islands,HffmnIsl,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,4743.128127,6.357020e+05,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
260,5,Staten Island,085,SI9592,Miller Field,MllrFld,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,19197.200973,1.086680e+07,"POLYGON ((960721.609 147492.642, 960370.525 14..."
261,5,Staten Island,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13..."

In [5]:
inc = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/income-censustracts.csv')

In [6]:
inc

            geoid    Tract County Name State  Median Income  Population
0     36005000100     1.00       Bronx    NY            NaN        6661
1     36005000200     2.00       Bronx    NY        72194.0        4453
2     36005000400     4.00       Bronx    NY       111250.0        6000
3     36005001600    16.00       Bronx    NY        49866.0        6038
4     36005001901    19.01       Bronx    NY        53065.0        2168
...           ...      ...         ...   ...            ...         ...
2322  36085030302   303.02    Richmond    NY        96163.0        6663
2323  36085031901   319.01    Richmond    NY        43569.0        3422
2324  36085031902   319.02    Richmond    NY       107009.0        5298
2325  36085032300   323.00    Richmond    NY       116875.0        1105
2326  36085990100  9901.00    Richmond    NY            NaN           0

[2327 rows x 6 columns]

In [7]:
gdf['County Name'] = gdf['County Name'].replace({'Staten Island': ' Richmond', 'Manhattan': ' New York', 'Brooklyn': ' Kings',  'Queens': ' Queens',  'Bronx': ' Bronx'})

In [8]:
gdf

,BoroCode,County Name,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry
0,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ..."
1,3,Kings,047,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28158.316197,2.886214e+07,"POLYGON ((994849.011 203499.267, 994911.093 20..."
2,3,Kings,047,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.280262,1.520896e+07,"POLYGON ((998047.210 196303.325, 998157.901 19..."
3,3,Kings,047,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.772815,5.226621e+07,"POLYGON ((1005302.497 199455.730, 1005307.792 ..."
4,3,Kings,047,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.504911,9.982322e+06,"POLYGON ((986367.735 190549.239, 985813.835 19..."
...,...,...,...,...,...,...,...,...,...,...,...,...
257,5,Richmond,085,SI0391,Freshkills Park (South),FrshklPK_S,9,SI03,SI03 South Shore (CD 3 Approximation),33945.420291,4.775877e+07,"POLYGON ((928531.433 150471.714, 929005.649 15..."
258,5,Richmond,085,SI9561,Fort Wadsworth,FtWdswrth,6,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,14816.104455,9.864874e+06,"POLYGON ((967656.829 155637.132, 967549.629 15..."
259,5,Richmond,085,SI9591,Hoffman & Swinburne Islands,HffmnIsl,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,4743.128127,6.357020e+05,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
260,5,Richmond,085,SI9592,Miller Field,MllrFld,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,19197.200973,1.086680e+07,"POLYGON ((960721.609 147492.642, 960370.525 14..."
261,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13..."

In [9]:
m = pd.merge(gdf, inc, on='County Name')

In [10]:
m

,BoroCode,County Name,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry,geoid,Tract,State,Median Income,Population
0,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000100,1.00,NY,230132.0,4722
1,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000200,2.00,NY,56477.0,1160
2,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000301,3.01,NY,250001.0,3892
3,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000501,5.01,NY,232625.0,4604
4,3,Kings,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000502,5.02,NY,236858.0,2826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147718,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085030302,303.02,NY,96163.0,6663
147719,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085031901,319.01,NY,43569.0,3422
147720,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085031902,319.02,NY,107009.0,5298
147721,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085032300,323.00,NY,116875.0,1105
147722,5,Richmond,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085990100,9901.00,NY,NaN,0

In [11]:
m.shape

(147723, 17)

In [12]:
m.columns

Index(['BoroCode', 'County Name', 'CountyFIPS', 'NTA2020', 'NTAName',
       'NTAAbbrev', 'NTAType', 'CDTA2020', 'CDTAName', 'Shape_Leng',
       'Shape_Area', 'geometry', 'geoid', 'Tract', 'State', 'Median Income',
       'Population'],
      dtype='object')

In [13]:
m = m.drop(['NTAAbbrev', 'NTAType', 'CDTA2020', 'CDTAName', 'Tract', 'State'], axis=1)

In [14]:
m

,BoroCode,County Name,CountyFIPS,NTA2020,NTAName,Shape_Leng,Shape_Area,geometry,geoid,Median Income,Population
0,3,Kings,047,BK0101,Greenpoint,28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000100,230132.0,4722
1,3,Kings,047,BK0101,Greenpoint,28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000200,56477.0,1160
2,3,Kings,047,BK0101,Greenpoint,28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000301,250001.0,3892
3,3,Kings,047,BK0101,Greenpoint,28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000501,232625.0,4604
4,3,Kings,047,BK0101,Greenpoint,28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ...",36047000502,236858.0,2826
...,...,...,...,...,...,...,...,...,...,...,...
147718,5,Richmond,085,SI9593,Great Kills Park,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085030302,96163.0,6663
147719,5,Richmond,085,SI9593,Great Kills Park,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085031901,43569.0,3422
147720,5,Richmond,085,SI9593,Great Kills Park,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085031902,107009.0,5298
147721,5,Richmond,085,SI9593,Great Kills Park,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085032300,116875.0,1105
147722,5,Richmond,085,SI9593,Great Kills Park,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13...",36085990100,NaN,0

In [15]:
m =  m.groupby(['NTAName'], as_index=False).mean()

In [16]:
m

,NTAName,BoroCode,Shape_Leng,Shape_Area,geoid,Median Income,Population
0,Allerton,2.0,17837.937333,1.575392e+07,3.600502e+10,60246.678466,4067.207756
1,Alley Pond Park,4.0,48184.402299,2.613240e+07,3.608106e+10,90949.882789,3300.833103
2,Annadale-Huguenot-Prince's Bay-Woodrow,5.0,67592.595333,1.804283e+08,3.608502e+10,108563.863248,3914.238095
3,Arden Heights-Rossville,5.0,38159.860824,6.777396e+07,3.608502e+10,108563.863248,3914.238095
4,Astoria (Central),4.0,21571.990905,2.108482e+07,3.608106e+10,90949.882789,3300.833103
...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,3.0,21234.300305,1.531205e+07,3.604705e+10,89900.035480,3369.391304
258,Woodhaven,4.0,21956.420913,2.372750e+07,3.608106e+10,90949.882789,3300.833103
259,Woodlawn Cemetery,2.0,18168.590667,1.788638e+07,3.600502e+10,60246.678466,4067.207756
260,Woodside,4.0,31737.888428,3.294947e+07,3.608106e+10,90949.882789,3300.833103
261,Yankee Stadium-Macombs Dam Park,2.0,9673.853546,2.808903e+06,3.600502e+10,60246.678466,4067.207756

In [17]:
grouped = m.groupby('NTAName')

weighted_avg = grouped.agg({'Median Income': lambda x: np.average(x, weights=m.loc[x.index, 'Population'])})

weighted_avg = weighted_avg.rename(columns={'Median Income': 'Weighted Avg Income'})

result = m.merge(weighted_avg, on='NTAName')

In [18]:
result

,NTAName,BoroCode,Shape_Leng,Shape_Area,geoid,Median Income,Population,Weighted Avg Income
0,Allerton,2.0,17837.937333,1.575392e+07,3.600502e+10,60246.678466,4067.207756,60246.678466
1,Alley Pond Park,4.0,48184.402299,2.613240e+07,3.608106e+10,90949.882789,3300.833103,90949.882789
2,Annadale-Huguenot-Prince's Bay-Woodrow,5.0,67592.595333,1.804283e+08,3.608502e+10,108563.863248,3914.238095,108563.863248
3,Arden Heights-Rossville,5.0,38159.860824,6.777396e+07,3.608502e+10,108563.863248,3914.238095,108563.863248
4,Astoria (Central),4.0,21571.990905,2.108482e+07,3.608106e+10,90949.882789,3300.833103,90949.882789
...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,3.0,21234.300305,1.531205e+07,3.604705e+10,89900.035480,3369.391304,89900.035480
258,Woodhaven,4.0,21956.420913,2.372750e+07,3.608106e+10,90949.882789,3300.833103,90949.882789
259,Woodlawn Cemetery,2.0,18168.590667,1.788638e+07,3.600502e+10,60246.678466,4067.207756,60246.678466
260,Woodside,4.0,31737.888428,3.294947e+07,3.608106e+10,90949.882789,3300.833103,90949.882789
261,Yankee Stadium-Macombs Dam Park,2.0,9673.853546,2.808903e+06,3.600502e+10,60246.678466,4067.207756,60246.678466

In [19]:
result.to_csv('Income.csv', index=False)