In [1]:
import pandas as pd 
import numpy as np 
import geopandas as gpd 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import censusdata
warnings.simplefilter(action="ignore", category=FutureWarning)
%matplotlib inline

In [2]:
income = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/FINALFINAL/Income.csv')

In [3]:
pea = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/FINALFINAL/Pov&EA.csv')

In [4]:
race = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/FINALFINAL/Race.csv')

In [5]:
sd = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/FINALFINAL/streetdensity.csv')

In [7]:
income.columns

Index(['NTAName_left', 'Population', 'Weighted Median Income'], dtype='object')

In [8]:
pea.columns

Index(['NTAName_x', 'Total Population_x', 'Below Poverty Line %',
       'Total Population_y', 'Less than 9th grade',
       '9th to 12th grade, no diploma', 'High school diploma', 'Some college',
       'Associate degree', 'Bachelor degree', 'Graduate degree',
       'High school graduate, or higher', 'Bachelor degree, or higher'],
      dtype='object')

In [9]:
race.columns

Index(['NTAName_y', 'Total', 'White, not hispanic',
       'Black or African American, not hispanic',
       'American Indian and Alaska Native, not hispanic',
       'Asain, not hispanic',
       'Native Hawaiian and Other Pacific Islander, not hispanic',
       'Some other race alone, not hispanic',
       'Two or More Races, not hispanic', 'Hispanic or Latino'],
      dtype='object')

In [12]:
sd.columns

Index(['NTAName', 'Normalized'], dtype='object')

In [10]:
race = race.rename(columns = {'NTAName_y':'NTAName'})

In [11]:
income = income.rename(columns = {'NTAName_left':'NTAName'})

In [13]:
pea = pea.rename(columns = {'NTAName_x':'NTAName'})

In [14]:
m = pd.merge(income, pea, on='NTAName')

In [15]:
mm = pd.merge(m, race, on='NTAName')

In [17]:
merged = pd.merge(mm, sd, on='NTAName')

In [19]:
merged = merged.rename(columns = {'Normalized':'NormalizedSD'})

In [20]:
merged

,NTAName,Population,Weighted Median Income,Total Population_x,Below Poverty Line %,Total Population_y,Less than 9th grade,"9th to 12th grade, no diploma",High school diploma,Some college,...,Total,"White, not hispanic","Black or African American, not hispanic","American Indian and Alaska Native, not hispanic","Asain, not hispanic","Native Hawaiian and Other Pacific Islander, not hispanic","Some other race alone, not hispanic","Two or More Races, not hispanic",Hispanic or Latino,NormalizedSD
0,Allerton,3117.473684,62141.291295,36057,24.602712,29883,209.785523,55.317248,41.823056,108.445040,...,62155,14.763092,38.169093,0.109404,4.709195,0.008044,0.933151,2.067412,39.240608,2.700146
1,Alley Pond Park,4118.636364,107518.289372,42,7.142857,39,0.000000,0.000000,0.000000,0.451722,...,90,65.555556,3.333333,0.000000,6.666667,0.000000,0.000000,0.000000,24.444444,1.627803
2,Annadale-Huguenot-Prince's Bay-Woodrow,5090.315789,126245.529571,44139,5.965246,35230,494.157303,62.471910,107.415730,240.299625,...,53872,72.772498,7.441714,0.252450,8.438521,0.000000,1.020939,1.522127,8.551752,0.235762
3,Arden Heights-Rossville,4266.533333,123022.836526,31583,4.344109,5547,36.519337,3.453039,4.640884,11.325967,...,30539,75.487082,0.533744,0.065490,7.881725,0.088412,0.160451,0.887390,14.895707,0.627650
4,Astoria (Central),3012.892857,99753.770961,47297,10.717382,46478,87.651438,9.122756,10.421836,34.068019,...,129518,48.189441,12.619868,0.175265,9.288284,0.006949,0.413842,2.672988,26.633364,2.017487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202,Williamsbridge-Olinville,3314.289474,57061.063497,61710,21.040350,57664,96.781679,20.298628,16.999596,53.621872,...,114951,16.928952,48.229246,0.474985,9.212621,0.156588,0.718567,2.015641,22.263399,1.173722
203,Williamsburg,4570.125000,119312.391337,63211,15.759915,57774,56.641958,13.448641,14.566420,38.216261,...,94307,47.328406,2.397489,0.010604,9.308959,0.033932,0.311748,3.087788,37.521075,1.473846
204,Windsor Terrace-South Slope,2884.850000,142219.077040,26973,7.881956,14065,12.206266,1.811358,2.774151,12.402089,...,51440,66.121695,5.223561,0.000000,9.758942,0.000000,0.573484,3.339813,14.982504,2.778086
205,Woodhaven,2885.523810,74809.918179,41906,9.869708,40462,270.961228,44.143780,43.134087,124.717286,...,114909,16.999539,7.339721,0.462975,31.157699,0.000000,0.865903,1.610840,41.563324,1.792787
206,Woodside,3329.875000,77868.121044,48421,7.275769,43000,536.002040,37.174911,50.790413,127.536971,...,197137,16.635132,17.036376,0.139497,13.109158,0.009131,0.497116,1.596352,50.977239,1.291016

In [21]:
#merged.to_csv('mergedregressors.csv', index=False)