In [2]:
import pandas as pd 
import numpy as np 
import geopandas as gpd 
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
%matplotlib inline

In [3]:
gdf = gpd.read_file('/Users/ananyarajesh/Downloads/nynta2020_23a/nynta2020.shp')

In [4]:
gdf.rename(columns={'BoroName': 'Borough'}, inplace=True)

In [5]:
gdf

,BoroCode,Borough,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry
0,3,Brooklyn,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ..."
1,3,Brooklyn,047,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28158.316197,2.886214e+07,"POLYGON ((994849.011 203499.267, 994911.093 20..."
2,3,Brooklyn,047,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.280262,1.520896e+07,"POLYGON ((998047.210 196303.325, 998157.901 19..."
3,3,Brooklyn,047,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.772815,5.226621e+07,"POLYGON ((1005302.497 199455.730, 1005307.792 ..."
4,3,Brooklyn,047,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.504911,9.982322e+06,"POLYGON ((986367.735 190549.239, 985813.835 19..."
...,...,...,...,...,...,...,...,...,...,...,...,...
257,5,Staten Island,085,SI0391,Freshkills Park (South),FrshklPK_S,9,SI03,SI03 South Shore (CD 3 Approximation),33945.420291,4.775877e+07,"POLYGON ((928531.433 150471.714, 929005.649 15..."
258,5,Staten Island,085,SI9561,Fort Wadsworth,FtWdswrth,6,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,14816.104455,9.864874e+06,"POLYGON ((967656.829 155637.132, 967549.629 15..."
259,5,Staten Island,085,SI9591,Hoffman & Swinburne Islands,HffmnIsl,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,4743.128127,6.357020e+05,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
260,5,Staten Island,085,SI9592,Miller Field,MllrFld,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,19197.200973,1.086680e+07,"POLYGON ((960721.609 147492.642, 960370.525 14..."
261,5,Staten Island,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13..."

In [6]:
df = pd.read_excel("/Users/ananyarajesh/Downloads/acs_demo_06to10_ntas.xlsx")

In [7]:
df

,GeoType,GeogName,GeoID,Borough,Pop1E,Pop1M,Pop1C,Pop1P,Pop1Z,MaleE,...,AsnOAsnE,AsnOAsnM,AsnOAsnC,AsnOAsnP,AsnOAsnZ,Asn2plE,Asn2plM,Asn2plC,Asn2plP,Asn2plZ
0,NTA2010,Allerton-Pelham Gardens,BX31,Bronx,31376,1360.0,2.6,100.0,NaN,15142,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NTA2010,Bedford Park-Fordham North,BX05,Bronx,50524,1909.0,2.3,100.0,NaN,23262,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NTA2010,Belmont,BX06,Bronx,26657,1433.0,3.3,100.0,NaN,12969,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NTA2010,Bronxdale,BX07,Bronx,33565,1354.0,2.5,100.0,NaN,15337,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NTA2010,Claremont-Bathgate,BX01,Bronx,29478,1344.0,2.8,100.0,NaN,13222,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,NTA2010,Rossville-Woodrow,SI32,Staten Island,19461,750.0,2.3,100.0,NaN,9613,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,NTA2010,Stapleton-Rosebank,SI37,Staten Island,24747,1285.0,3.2,100.0,NaN,12380,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,NTA2010,Todt Hill-Emerson Hill-Heartland Village-Light...,SI24,Staten Island,32489,1292.0,2.4,100.0,NaN,15434,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,NTA2010,West New Brighton-New Brighton-St. George,SI22,Staten Island,30879,1558.0,3.1,100.0,NaN,14902,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,NTA2010,Westerleigh,SI07,Staten Island,23966,833.0,2.1,100.0,NaN,11758,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns

Index(['GeoType', 'GeogName', 'GeoID', 'Borough', 'Pop1E', 'Pop1M', 'Pop1C',
       'Pop1P', 'Pop1Z', 'MaleE',
       ...
       'AsnOAsnE', 'AsnOAsnM', 'AsnOAsnC', 'AsnOAsnP', 'AsnOAsnZ', 'Asn2plE',
       'Asn2plM', 'Asn2plC', 'Asn2plP', 'Asn2plZ'],
      dtype='object', length=484)

In [9]:
df10 = df[['GeogName', 'GeoID', 'Borough', 'Pop1E', 'MaleE', 'FemE', 'Hsp1E', 'NHspE', 'WtNHE', 'BlNHE', 'AIANNHE', 'AsnNHE', 'NHPINHE', 'OthNHE', 'Rc2plNHE']]

In [10]:
df10

,GeogName,GeoID,Borough,Pop1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE
0,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,54,2736,0,192,401
1,Bedford Park-Fordham North,BX05,Bronx,50524,23262,27262,35504,15020,3237,8395,48,2227,0,805,308
2,Belmont,BX06,Bronx,26657,12969,13688,16672,9985,4676,4366,0,769,0,86,88
3,Bronxdale,BX07,Bronx,33565,15337,18228,15827,17738,5993,9957,117,1226,0,152,293
4,Claremont-Bathgate,BX01,Bronx,29478,13222,16256,16950,12528,286,12072,40,35,0,57,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Rossville-Woodrow,SI32,Staten Island,19461,9613,9848,1721,17740,16730,72,18,810,0,0,110
191,Stapleton-Rosebank,SI37,Staten Island,24747,12380,12367,6824,17923,9885,4568,0,3277,0,10,183
192,Todt Hill-Emerson Hill-Heartland Village-Light...,SI24,Staten Island,32489,15434,17055,2232,30257,24526,920,12,4716,0,34,49
193,West New Brighton-New Brighton-St. George,SI22,Staten Island,30879,14902,15977,9629,21250,8193,10866,23,1577,0,54,537
194,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,21,1738,0,87,485

In [11]:
df21 = pd.read_excel("/Users/ananyarajesh/Downloads/demo_2021acs5yr_nta.xlsx")

In [12]:
df21

,GeoType,NTAType,GeogName,GeoID,Borough,Pop_1E,Pop_1M,Pop_1C,Pop_1P,Pop_1Z,...,AsnOAsnE,AsnOAsnM,AsnOAsnC,AsnOAsnP,AsnOAsnZ,Asn2plE,Asn2plM,Asn2plC,Asn2plP,Asn2plZ
0,NTA2020,0,Greenpoint,BK0101,Brooklyn,37518,1616.0,2.6,100.0,0.0,...,29,28.0,58.6,1.9,1.8,73,65.0,53.9,4.9,4.2
1,NTA2020,0,Williamsburg,BK0102,Brooklyn,63316,2630.0,2.5,100.0,0.0,...,72,74.0,62.6,1.4,1.5,189,106.0,34.1,3.8,2.0
2,NTA2020,0,South Williamsburg,BK0103,Brooklyn,47065,3700.0,4.8,100.0,0.0,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
3,NTA2020,0,East Williamsburg,BK0104,Brooklyn,53478,2471.0,2.8,100.0,0.0,...,47,41.0,52.7,1.0,0.8,123,89.0,44.0,2.5,1.8
4,NTA2020,0,Brooklyn Heights,BK0201,Brooklyn,24775,1331.0,3.3,100.0,0.0,...,0,NaN,NaN,NaN,NaN,74,56.0,46.2,4.0,2.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,NTA2020,9,Freshkills Park (North),SI0291,Staten Island,0,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
258,NTA2020,9,Freshkills Park (South),SI0391,Staten Island,23,17.0,44.9,100.0,0.0,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
259,NTA2020,9,Hoffman & Swinburne Islands,SI9591,Staten Island,0,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
260,NTA2020,9,Miller Field,SI9592,Staten Island,260,265.0,62.0,100.0,0.0,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
261,NTA2020,9,Great Kills Park,SI9593,Staten Island,0,NaN,NaN,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [13]:
df21 = df21[['GeogName', 'GeoID', 'Borough', 'Pop_1E', 'MaleE', 'FemE', 'Hsp1E', 'NHspE', 'WtNHE', 'BlNHE', 'AIANNHE', 'AsnNHE', 'NHPINHE', 'OthNHE', 'Rc2plNHE']]

In [14]:
df21

,GeogName,GeoID,Borough,Pop_1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE
0,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,22,1464,0,210,2114
1,Williamsburg,BK0102,Brooklyn,63316,31861,31455,18908,44408,34827,1395,11,4905,0,248,3022
2,South Williamsburg,BK0103,Brooklyn,47065,23651,23414,3957,43108,40619,1571,0,237,0,264,417
3,East Williamsburg,BK0104,Brooklyn,53478,25752,27726,20099,33379,20302,6439,58,4865,0,172,1543
4,Brooklyn Heights,BK0201,Brooklyn,24775,11517,13258,1722,23053,18465,1337,78,1846,0,73,1254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Freshkills Park (North),SI0291,Staten Island,0,0,0,0,0,0,0,0,0,0,0,0
258,Freshkills Park (South),SI0391,Staten Island,23,23,0,0,23,18,5,0,0,0,0,0
259,Hoffman & Swinburne Islands,SI9591,Staten Island,0,0,0,0,0,0,0,0,0,0,0,0
260,Miller Field,SI9592,Staten Island,260,59,201,74,186,14,172,0,0,0,0,0
261,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,0,0,0,0,0

In [15]:
merged_df10 = df10.merge(gdf, on='Borough')

In [16]:
merged_df10

,GeogName,GeoID,Borough,Pop1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,...,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry
0,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,...,005,BX0101,Mott Haven-Port Morris,MttHvn,0,BX01,BX01 Melrose-Mott Haven-Port Morris (CD 1 Appr...,29217.823011,4.097465e+07,"POLYGON ((1004958.078 237310.063, 1004672.025 ..."
1,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,...,005,BX0102,Melrose,Mlrs,0,BX01,BX01 Melrose-Mott Haven-Port Morris (CD 1 Appr...,19589.195636,1.727176e+07,"POLYGON ((1011570.155 238213.890, 1011485.105 ..."
2,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,...,005,BX0201,Hunts Point,HntsPt,0,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),37430.317447,4.503886e+07,"POLYGON ((1017193.342 237404.830, 1018001.905 ..."
3,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,...,005,BX0202,Longwood,Lngwd,0,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),21721.755676,1.538515e+07,"POLYGON ((1015322.558 238911.310, 1015154.964 ..."
4,Allerton-Pelham Gardens,BX31,Bronx,31376,15142,16234,9442,21934,9000,9551,...,005,BX0291,North & South Brother Islands,BrthrIsls,9,BX02,BX02 Longwood-Hunts Point (CD 2 Approximation),6884.551373,9.306492e+05,"MULTIPOLYGON (((1012821.806 229228.265, 101278..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11709,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,...,085,SI0391,Freshkills Park (South),FrshklPK_S,9,SI03,SI03 South Shore (CD 3 Approximation),33945.420291,4.775877e+07,"POLYGON ((928531.433 150471.714, 929005.649 15..."
11710,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,...,085,SI9561,Fort Wadsworth,FtWdswrth,6,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,14816.104455,9.864874e+06,"POLYGON ((967656.829 155637.132, 967549.629 15..."
11711,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,...,085,SI9591,Hoffman & Swinburne Islands,HffmnIsl,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,4743.128127,6.357020e+05,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
11712,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,...,085,SI9592,Miller Field,MllrFld,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,19197.200973,1.086680e+07,"POLYGON ((960721.609 147492.642, 960370.525 14..."
11713,Westerleigh,SI07,Staten Island,23966,11758,12208,2805,21161,18412,418,...,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13..."

In [17]:
merged_df21 = df21.merge(gdf, on='Borough')

In [18]:
merged_df21

,GeogName,GeoID,Borough,Pop_1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,...,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area,geometry
0,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,...,047,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28914.172236,3.532185e+07,"POLYGON ((1003059.997 204572.025, 1002991.367 ..."
1,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,...,047,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28158.316197,2.886214e+07,"POLYGON ((994849.011 203499.267, 994911.093 20..."
2,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,...,047,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.280262,1.520896e+07,"POLYGON ((998047.210 196303.325, 998157.901 19..."
3,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,...,047,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.772815,5.226621e+07,"POLYGON ((1005302.497 199455.730, 1005307.792 ..."
4,Greenpoint,BK0101,Brooklyn,37518,18545,18973,5498,32020,27273,937,...,047,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.504911,9.982322e+06,"POLYGON ((986367.735 190549.239, 985813.835 19..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15985,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,...,085,SI0391,Freshkills Park (South),FrshklPK_S,9,SI03,SI03 South Shore (CD 3 Approximation),33945.420291,4.775877e+07,"POLYGON ((928531.433 150471.714, 929005.649 15..."
15986,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,...,085,SI9561,Fort Wadsworth,FtWdswrth,6,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,14816.104455,9.864874e+06,"POLYGON ((967656.829 155637.132, 967549.629 15..."
15987,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,...,085,SI9591,Hoffman & Swinburne Islands,HffmnIsl,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,4743.128127,6.357020e+05,"MULTIPOLYGON (((970217.022 145643.332, 970227...."
15988,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,...,085,SI9592,Miller Field,MllrFld,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,19197.200973,1.086680e+07,"POLYGON ((960721.609 147492.642, 960370.525 14..."
15989,Great Kills Park,SI9593,Staten Island,0,0,0,0,0,0,0,...,085,SI9593,Great Kills Park,GrtKlsPk,9,SI95,SI95 Great Kills Park-Fort Wadsworth (JIA 95 A...,41465.430028,2.337791e+07,"POLYGON ((952739.319 138974.819, 952732.507 13..."

In [19]:
grouped10 = merged_df10.groupby(['NTAName', 'Borough'], as_index=False).mean()
grouped10

,NTAName,Borough,Pop1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE,BoroCode,Shape_Leng,Shape_Area
0,Allerton,Bronx,35940.131579,16836.236842,19103.894737,18900.105263,17040.026316,4118.131579,10984.315789,74.815789,1247.394737,2.710526,294.315789,318.342105,2.0,17837.937333,1.575392e+07
1,Alley Pond Park,Queens,37916.706897,18330.862069,19585.844828,10226.551724,27690.155172,10842.775862,6816.172414,108.448276,8698.000000,12.620690,672.310345,539.827586,4.0,48184.402299,2.613240e+07
2,Annadale-Huguenot-Prince's Bay-Woodrow,Staten Island,24392.105263,11824.894737,12567.210526,3979.052632,20413.052632,15949.210526,2309.263158,26.631579,1835.263158,0.000000,60.421053,232.263158,5.0,67592.595333,1.804283e+08
3,Arden Heights-Rossville,Staten Island,24392.105263,11824.894737,12567.210526,3979.052632,20413.052632,15949.210526,2309.263158,26.631579,1835.263158,0.000000,60.421053,232.263158,5.0,38159.860824,6.777396e+07
4,Astoria (Central),Queens,37916.706897,18330.862069,19585.844828,10226.551724,27690.155172,10842.775862,6816.172414,108.448276,8698.000000,12.620690,672.310345,539.827586,4.0,21571.990905,2.108482e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,Brooklyn,48368.274510,22772.705882,25595.568627,9552.882353,38815.392157,17232.490196,15848.333333,74.647059,4902.098039,12.470588,218.294118,527.058824,3.0,21234.300305,1.531205e+07
258,Woodhaven,Queens,37916.706897,18330.862069,19585.844828,10226.551724,27690.155172,10842.775862,6816.172414,108.448276,8698.000000,12.620690,672.310345,539.827586,4.0,21956.420913,2.372750e+07
259,Woodlawn Cemetery,Bronx,35940.131579,16836.236842,19103.894737,18900.105263,17040.026316,4118.131579,10984.315789,74.815789,1247.394737,2.710526,294.315789,318.342105,2.0,18168.590667,1.788638e+07
260,Woodside,Queens,37916.706897,18330.862069,19585.844828,10226.551724,27690.155172,10842.775862,6816.172414,108.448276,8698.000000,12.620690,672.310345,539.827586,4.0,31737.888428,3.294947e+07
261,Yankee Stadium-Macombs Dam Park,Bronx,35940.131579,16836.236842,19103.894737,18900.105263,17040.026316,4118.131579,10984.315789,74.815789,1247.394737,2.710526,294.315789,318.342105,2.0,9673.853546,2.808903e+06

In [20]:
grouped21 = merged_df21.groupby(['NTAName', 'Borough'], as_index=False).mean()
grouped21

,NTAName,Borough,Pop_1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE,BoroCode,Shape_Leng,Shape_Area
0,Allerton,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,17837.937333,1.575392e+07
1,Alley Pond Park,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,48184.402299,2.613240e+07
2,Annadale-Huguenot-Prince's Bay-Woodrow,Staten Island,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,67592.595333,1.804283e+08
3,Arden Heights-Rossville,Staten Island,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,38159.860824,6.777396e+07
4,Astoria (Central),Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21571.990905,2.108482e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,Brooklyn,39309.565217,18724.275362,20585.289855,7384.449275,31925.115942,14439.623188,11254.797101,48.811594,4618.637681,16.463768,258.768116,1288.014493,3.0,21234.300305,1.531205e+07
258,Woodhaven,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21956.420913,2.372750e+07
259,Woodlawn Cemetery,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,18168.590667,1.788638e+07
260,Woodside,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,31737.888428,3.294947e+07
261,Yankee Stadium-Macombs Dam Park,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,9673.853546,2.808903e+06

In [21]:
grouped21.columns

Index(['NTAName', 'Borough', 'Pop_1E', 'MaleE', 'FemE', 'Hsp1E', 'NHspE',
       'WtNHE', 'BlNHE', 'AIANNHE', 'AsnNHE', 'NHPINHE', 'OthNHE', 'Rc2plNHE',
       'BoroCode', 'Shape_Leng', 'Shape_Area'],
      dtype='object')

grouped10.to_csv('2010-NTA-demographics.csv', index=False)

grouped21.to_csv('2021-NTA-demographics.csv', index=False)

In [22]:
merged_df21.columns

Index(['GeogName', 'GeoID', 'Borough', 'Pop_1E', 'MaleE', 'FemE', 'Hsp1E',
       'NHspE', 'WtNHE', 'BlNHE', 'AIANNHE', 'AsnNHE', 'NHPINHE', 'OthNHE',
       'Rc2plNHE', 'BoroCode', 'CountyFIPS', 'NTA2020', 'NTAName', 'NTAAbbrev',
       'NTAType', 'CDTA2020', 'CDTAName', 'Shape_Leng', 'Shape_Area',
       'geometry'],
      dtype='object')

In [23]:
grouped21

,NTAName,Borough,Pop_1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE,BoroCode,Shape_Leng,Shape_Area
0,Allerton,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,17837.937333,1.575392e+07
1,Alley Pond Park,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,48184.402299,2.613240e+07
2,Annadale-Huguenot-Prince's Bay-Woodrow,Staten Island,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,67592.595333,1.804283e+08
3,Arden Heights-Rossville,Staten Island,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,38159.860824,6.777396e+07
4,Astoria (Central),Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21571.990905,2.108482e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,Brooklyn,39309.565217,18724.275362,20585.289855,7384.449275,31925.115942,14439.623188,11254.797101,48.811594,4618.637681,16.463768,258.768116,1288.014493,3.0,21234.300305,1.531205e+07
258,Woodhaven,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21956.420913,2.372750e+07
259,Woodlawn Cemetery,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,18168.590667,1.788638e+07
260,Woodside,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,31737.888428,3.294947e+07
261,Yankee Stadium-Macombs Dam Park,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,9673.853546,2.808903e+06

In [25]:
inc = pd.read_csv('/Users/ananyarajesh/Desktop/MLC_Data/income-censustracts.csv')

In [26]:
inc

            geoid    Tract County Name State  Median Income  Population
0     36005000100     1.00       Bronx    NY            NaN        6661
1     36005000200     2.00       Bronx    NY        72194.0        4453
2     36005000400     4.00       Bronx    NY       111250.0        6000
3     36005001600    16.00       Bronx    NY        49866.0        6038
4     36005001901    19.01       Bronx    NY        53065.0        2168
...           ...      ...         ...   ...            ...         ...
2322  36085030302   303.02    Richmond    NY        96163.0        6663
2323  36085031901   319.01    Richmond    NY        43569.0        3422
2324  36085031902   319.02    Richmond    NY       107009.0        5298
2325  36085032300   323.00    Richmond    NY       116875.0        1105
2326  36085990100  9901.00    Richmond    NY            NaN           0

[2327 rows x 6 columns]

In [27]:
incg =  inc.groupby(['County Name'], as_index=False).mean()

In [28]:
incg

  County Name         geoid       Tract  Median Income   Population
0       Bronx  3.600502e+10  247.674155   60246.678466  4067.207756
1       Kings  3.604705e+10  508.442770   89900.035480  3369.391304
2    New York  3.606101e+10  141.589484  151712.302491  5384.280645
3      Queens  3.608106e+10  568.046317   90949.882789  3300.833103
4    Richmond  3.608502e+10  228.324444  108563.863248  3914.238095

In [29]:
grouped21 = grouped21.rename(columns={'Borough': 'County Name'})

In [30]:
grouped21['County Name'] = grouped21['County Name'].replace({'Staten Island': ' Richmond', 'Manhattan': ' New York', 'Brooklyn': ' Kings',  'Queens': ' Queens',  'Bronx': ' Bronx'})

In [31]:
grouped21

,NTAName,County Name,Pop_1E,MaleE,FemE,Hsp1E,NHspE,WtNHE,BlNHE,AIANNHE,AsnNHE,NHPINHE,OthNHE,Rc2plNHE,BoroCode,Shape_Leng,Shape_Area
0,Allerton,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,17837.937333,1.575392e+07
1,Alley Pond Park,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,48184.402299,2.613240e+07
2,Annadale-Huguenot-Prince's Bay-Woodrow,Richmond,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,67592.595333,1.804283e+08
3,Arden Heights-Rossville,Richmond,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,38159.860824,6.777396e+07
4,Astoria (Central),Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21571.990905,2.108482e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,Kings,39309.565217,18724.275362,20585.289855,7384.449275,31925.115942,14439.623188,11254.797101,48.811594,4618.637681,16.463768,258.768116,1288.014493,3.0,21234.300305,1.531205e+07
258,Woodhaven,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21956.420913,2.372750e+07
259,Woodlawn Cemetery,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,18168.590667,1.788638e+07
260,Woodside,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,31737.888428,3.294947e+07
261,Yankee Stadium-Macombs Dam Park,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,9673.853546,2.808903e+06

In [32]:
grouped21.columns

Index(['NTAName', 'County Name', 'Pop_1E', 'MaleE', 'FemE', 'Hsp1E', 'NHspE',
       'WtNHE', 'BlNHE', 'AIANNHE', 'AsnNHE', 'NHPINHE', 'OthNHE', 'Rc2plNHE',
       'BoroCode', 'Shape_Leng', 'Shape_Area'],
      dtype='object')

In [35]:
grouped21 = grouped21.rename(columns={'Pop_1E': 'Population',
                                      'MaleE': 'Male_Pop',
                                     'FemE': 'Female_Pop',
                                     'Hsp1E': 'Hsp_Pop',
                                     'NHspE': 'Not_Hsp_Pop',
                                     'WtNHE': 'White_Pop', 
                                     'BlNHE': 'Black_Pop', 
                                     'AIANNHE': 'AmericanIndian_AlaskaNative_Pop', 
                                     'AsnNHE': 'Asian_Pop', 
                                     'NHPINHE': 'NativeHawaiian_Pop', 
                                     'OthNHE': 'Other_Pop',
                                     'Rc2plNHE': 'Two+_Pop'})

In [36]:
grouped21

,NTAName,County Name,Total Population,Male_Pop,Female_Pop,Hsp_Pop,Not_Hsp_Pop,White_Pop,Black_Pop,AmericanIndian_AlaskanNative_Pop,Asian_Pop,NativeHawaiian_Pop,Other_Pop,Two+_Pop,BoroCode,Shape_Leng,Shape_Area
0,Allerton,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,17837.937333,1.575392e+07
1,Alley Pond Park,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,48184.402299,2.613240e+07
2,Annadale-Huguenot-Prince's Bay-Woodrow,Richmond,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,67592.595333,1.804283e+08
3,Arden Heights-Rossville,Richmond,21443.217391,10467.608696,10975.608696,3954.652174,17488.565217,12788.608696,1949.956522,29.217391,2221.782609,0.000000,45.739130,453.260870,5.0,38159.860824,6.777396e+07
4,Astoria (Central),Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21571.990905,2.108482e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Windsor Terrace-South Slope,Kings,39309.565217,18724.275362,20585.289855,7384.449275,31925.115942,14439.623188,11254.797101,48.811594,4618.637681,16.463768,258.768116,1288.014493,3.0,21234.300305,1.531205e+07
258,Woodhaven,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,21956.420913,2.372750e+07
259,Woodlawn Cemetery,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,18168.590667,1.788638e+07
260,Woodside,Queens,28912.831325,14155.301205,14757.530120,8075.240964,20837.590361,7098.951807,4884.253012,77.843373,7380.578313,9.240964,571.156627,815.566265,4.0,31737.888428,3.294947e+07
261,Yankee Stadium-Macombs Dam Park,Bronx,30068.448980,14181.734694,15886.714286,16957.122449,13111.326531,2680.673469,8508.102041,69.673469,1102.306122,6.367347,267.612245,476.591837,2.0,9673.853546,2.808903e+06

In [38]:
#grouped21.to_csv('Race.csv', index=False)